import argparse
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, select_autoescape

from scripts.content_model import THEMES, load_json
from scripts.fetch_pubmed import fetch_works
from scripts.fetch_youtube import fetch_videos


ROOT = Path(__file__).resolve().parent
DATA = ROOT / "data"
PIPELINE = ROOT / "_pipeline"
TEMPLATES = ROOT / "templates"
BASE_URL = "https://ahn-lab.org"

AUTHOR = {
    "name": "안상진 (Sangzin Ahn)",
    "title": "인제대학교 의과대학 약리학교실 부교수",
    "affiliations": [
        "Department of Pharmacology, Inje University College of Medicine, Busan, Korea",
        "Cardiovascular and Metabolic Diseases Medical Research Center, Inje University College of Medicine, Busan, Korea",
    ],
    "research_interests": [
        "대형언어모델의 의학 지식 표현 및 추론 평가 (Evaluation of Medical Knowledge Representation and Reasoning in LLMs)",
        "의학교육에서 대형언어모델 활용 (LLMs in Medical Education)",
    ],
    "education": [
        "2016.03-현재: 인제대학교 의과대학 약리학교실 교수",
        "2009.03-2016.02: 의학박사, 서울대학교 의과학과 약리학 전공",
        "2003.03-2009.02: 의학사, 서울대학교 의과대학",
    ],
    "announcement": "정말 죄송하게도 경남 일대를 제외한 지역은 이동 시간과 체력적인 부담, 지방 연자를 위한 배려가 부족한 강연료 규정 등의 이유로 현장강의를 고사하고 있습니다. 부디 너그러운 양해 부탁드립니다.",
    "scholar": "https://scholar.google.com/citations?hl=ko&user=Xe825ZgAAAAJ&view_op=list_works&sortby=pubdate",
    "orcid": "https://orcid.org/0000-0003-2749-0014",
    "youtube": "https://youtube.com/playlist?list=PL0TnWnPQhDj2-TOwiz_ZhY2Sdurimss2Q",
    "blog": "https://largelearningmodel.wordpress.com/",
}

PROJECTS = [
    {"name": "똑똑 자가검침 AI", "url": "/ttokttok/", "description": "도시가스 이력 조회와 검침값 제출을 한곳에서 관리하는 Android 앱입니다. 부산도시가스는 마지막 날 자동 제출도 선택할 수 있습니다."},
    {"name": "Google Timeline Visualizer", "url": "/google-timeline-visualizer/", "description": "위치 파일을 브라우저 밖으로 전송하지 않고 Google 지도 타임라인의 이동 기록을 애니메이션으로 시각화하는 도구입니다."},
    {
        "name": "ScholarRelay",
        "url": "https://chromewebstore.google.com/detail/epopghhfmpokhbalmnfcopmplffphdbb",
        "description": "PDF·논문·웹페이지를 Gemini Notebook(구 NotebookLM)에 추가하고, 노트북 정리와 오디오·영상·퀴즈 등 결과물 생성을 한 번에 진행하는 Chrome 확장 프로그램입니다.",
        "details": "논문 제목 자동 인식, 기존 컬렉션 선택, 로컬 PDF 업로드를 지원합니다.",
        "links": [
            {"label": "Chrome 웹 스토어에서 설치", "url": "https://chromewebstore.google.com/detail/epopghhfmpokhbalmnfcopmplffphdbb"},
            {"label": "GitHub", "url": "https://github.com/mahlernim/scholar-relay"},
            {"label": "개발 과정", "url": "https://github.com/mahlernim/scholar-relay/blob/main/docs/DEVELOPMENT.md"},
        ],
    },
    {"name": "Memori", "url": "https://memori.co.kr/", "description": "의학과 학습을 위한 암기법과 기억 단서를 모으는 커뮤니티입니다."},
    {"name": "Sakang", "url": "https://sakang.mahler83.net/", "description": "텍스트 정리, 임상 계산, 문서 및 교육 기록을 위한 소규모 도구 모음입니다."},
    {"name": "EduKMA", "url": "https://edukma.mahler83.net/", "description": "국내 온라인 보수교육 과정을 찾는 서비스입니다."},
    {"name": "LargeLearningModel", "url": "https://largelearningmodel.wordpress.com/", "description": "언어모델, 학습, 교육에 관한 글과 2008년부터 이어진 개인 기록입니다."},
    {"name": "Arithmetic Puzzle", "url": "https://arithmeticpuzzle.mahler83.net/", "description": "자연수와 기본 연산을 이용한 4×4 산술 퍼즐 생성기입니다."},
    {"name": "Home Assistant NEIS School", "url": "https://github.com/mahlernim/ha-neis-school", "description": "학교 급식, 시간표, 학사일정 및 출석 정보를 제공하는 Home Assistant 연동 기능입니다."},
    {"name": "Korean Twitter Activity Archive", "url": "https://tka.mahler83.net/", "description": "한국어 트위터 계정의 활동 변화를 익명화된 공개 데이터로 기록한 아카이브입니다."},
    {"name": "Tweet Earthquake Alert Archive", "url": "https://jijin.mahler83.net/", "description": "다수 이용자의 집단 반응을 통해 지진을 감지했던 프로젝트의 기록입니다."},
]


def environment():
    env = Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=select_autoescape(["html", "xml"]),
        trim_blocks=True,
        lstrip_blocks=True,
    )
    env.filters["from_json"] = json.loads
    env.globals["breadcrumb_schema"] = breadcrumb_schema
    return env


def breadcrumb_schema(items):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": position, "name": name, "item": f"{BASE_URL}{path}"}
            for position, (name, path) in enumerate(items, start=1)
        ],
    }


def summary_for(content, key):
    record = content.get("items", {}).get(key, {})
    return record if record.get("status") == "ready" else record or {"status": "pending_source"}


def remove_generation_disclosures(post):
    post = dict(post)
    disclosure = re.compile(r"\bthis (?:article|post) (?:was|is) generated by (?:ai|chatgpt)\b", re.I)
    post["sections"] = [
        section for section in post.get("sections", [])
        if not disclosure.search(" ".join([section.get("heading", ""), *section.get("paragraphs", []), *section.get("bullets", [])]))
    ]
    return post


def render(env, template_name, output, **context):
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        env.get_template(template_name).render(
            author=AUTHOR,
            themes=THEMES,
            base_url=BASE_URL,
            build_year=datetime.now(timezone.utc).year,
            **context,
        ),
        encoding="utf-8",
        newline="\n",
    )


def build_site(offline=False):
    if offline:
        publications = list(load_json(DATA / "publications_cache.json", {}).values())
        videos = list(load_json(DATA / "videos_cache.json", {}).values())
        videos.sort(key=lambda item: item.get("playlist_position", 999999))
    else:
        publications = fetch_works()
        videos = fetch_videos()
    publications.sort(key=lambda item: (item.get("year", 0), item.get("pmid", "")), reverse=True)
    content = load_json(PIPELINE / "generated_content.json", {"schema_version": 1, "items": {}})
    posts = list(load_json(PIPELINE / "posts.json", {"items": {}}).get("items", {}).values())
    posts = [remove_generation_disclosures(post) for post in posts if post.get("status") == "ready"]
    if len(posts) != 50:
        posts = []
    posts.sort(key=lambda item: item.get("published_at", ""), reverse=True)
    env = environment()

    for item in videos:
        item["generated"] = summary_for(content, f"video:{item['video_id']}")
        summary = item["generated"].get("summary", {}).get("ko", {}).get("overview", "")
        item["seo_description"] = summary or f"{item['title']} 강의 영상과 내용 요약"
    for item in publications:
        item["generated"] = summary_for(content, f"publication:{item['pmid']}")

    render(env, "index.html", ROOT / "index.html", page="home", posts=posts[:5], videos=videos[:3], publications=publications[:6], projects=PROJECTS[:5])
    render(env, "posts.html", ROOT / "posts" / "index.html", page="posts", posts=posts)
    for item in posts:
        render(env, "post_detail.html", ROOT / "posts" / str(item["wordpress_id"]) / "index.html", page="posts", post=item)
    render(env, "videos.html", ROOT / "videos" / "index.html", page="videos", videos=videos)
    for item in videos:
        render(env, "video_detail.html", ROOT / "videos" / item["video_id"] / "index.html", page="videos", video=item)
    render(env, "publications.html", ROOT / "publications" / "index.html", page="publications", publications=publications)
    for item in publications:
        render(env, "publication_detail.html", ROOT / "publications" / item["pmid"] / "index.html", page="publications", publication=item)
    render(env, "projects.html", ROOT / "projects" / "index.html", page="projects", projects=PROJECTS)
    write_sitemap(videos, publications, posts)


def write_sitemap(videos, publications, posts):
    routes = [(route, "") for route in ["/", "/posts/", "/videos/", "/publications/", "/projects/", "/google-timeline-visualizer/", "/ttokttok/"]]
    routes += [(f"/posts/{item['wordpress_id']}/", item.get("original_modified_at", "")[:10]) for item in posts]
    routes += [(f"/videos/{item['video_id']}/", item.get("upload_date", "")[:10]) for item in videos]
    routes += [(f"/publications/{item['pmid']}/", "") for item in publications]
    body = "\n".join(
        f"  <url><loc>{BASE_URL}{route}</loc>{f'<lastmod>{lastmod}</lastmod>' if lastmod else ''}</url>"
        for route, lastmod in routes
    )
    (ROOT / "sitemap.xml").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{body}\n</urlset>\n",
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()
    build_site(offline=args.offline)
